[build]
builder = "nixpacks"
buildCommand = "bun install && bun run build"

[deploy]
startCommand = "bun dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
NODE_ENV = "production" 