[build]
builder = "nixpacks"
buildCommand = "bun install && bun run build"

[deploy]
startCommand = "bun dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
NODE_ENV = "production"

# Railway automatically exposes the DATABASE_URL from your 
# linked Postgres service in the environment 